name = "lighthouse-studio"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "lighthouse-studio-db"
database_id = "d832833c-387f-422c-a515-e4c66e4ec289"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "lighthouse-studio-media"
